<?php

if (!function_exists('vn_admin_translate')) {
    function vn_admin_translate($html)
    {
        $map = array(
            '>Admin Panel<' => '>Trang quản trị<',
            '>Toggle navigation<' => '>Bật/tắt điều hướng<',
            '>Edit Profile<' => '>Chỉnh sửa hồ sơ<',
            '>Log out<' => '>Đăng xuất<',
            '>Dashboard<' => '>Tổng quan<',
            '>Website Settings<' => '>Cài đặt website<',
            '>Shop Settings<' => '>Cài đặt cửa hàng<',
            '>Size<' => '>Kích cỡ<',
            '>Color<' => '>Màu sắc<',
            '>Country<' => '>Quốc gia<',
            '>Shipping Cost<' => '>Phí vận chuyển<',
            '>Top Level Category<' => '>Danh mục cấp 1<',
            '>Mid Level Category<' => '>Danh mục cấp 2<',
            '>End Level Category<' => '>Danh mục cấp 3<',
            '>Product Management<' => '>Quản lý sản phẩm<',
            '>Order Management<' => '>Quản lý đơn hàng<',
            '>Manage Sliders<' => '>Quản lý slider<',
            '>Services<' => '>Dịch vụ<',
            '>Registered Customer<' => '>Khách hàng đã đăng ký<',
            '>Page Settings<' => '>Cài đặt trang<',
            '>Setup Language<' => '>Thiết lập ngôn ngữ<',
            '>Basic<' => '>Cơ bản<',
            '>Registration<' => '>Đăng ký<',
            '>Cart and Checkout<' => '>Giỏ hàng và thanh toán<',
            '>Payment<' => '>Thanh toán<',
            '>Login<' => '>Đăng nhập<',
            '>Log In<' => '>Đăng nhập<',
            '>Log in to start your session<' => '>Đăng nhập để bắt đầu phiên làm việc<',
            '>Email and/or Password can not be empty<' => '>Email hoặc mật khẩu không được để trống<',
            '>Email Address does not match<' => '>Email không đúng<',
            '>Password does not match<' => '>Mật khẩu không đúng<',
            '>Email address<' => '>Địa chỉ email<',
            '>Password<' => '>Mật khẩu<',
            '>Products<' => '>Sản phẩm<',
            '>Pending Orders<' => '>Đơn hàng chờ xử lý<',
            '>Completed Orders<' => '>Đơn hàng hoàn tất<',
            '>Completed Shipping<' => '>Giao hàng hoàn tất<',
            '>Pending Shippings<' => '>Giao hàng chờ xử lý<',
            '>Active Customers<' => '>Khách hàng đang hoạt động<',
            '>Available Shippings<' => '>Tuyến giao hàng khả dụng<',
            '>Top Categories<' => '>Danh mục cấp 1<',
            '>Mid Categories<' => '>Danh mục cấp 2<',
            '>End Categories<' => '>Danh mục cấp 3<',
            '>Settings<' => '>Cài đặt<',
            '>Profile<' => '>Hồ sơ<',
            '>Logout<' => '>Đăng xuất<',
            '>Save<' => '>Lưu<',
            '>Submit<' => '>Gửi<',
            '>Update<' => '>Cập nhật<',
            '>Delete<' => '>Xóa<',
            '>Add<' => '>Thêm<',
            '>Edit<' => '>Sửa<',
            '>Search<' => '>Tìm kiếm<',
            '>Status<' => '>Trạng thái<',
            '>Active<' => '>Hoạt động<',
            '>Inactive<' => '>Tạm khóa<',
            '>Pending<' => '>Chờ xử lý<',
            '>Completed<' => '>Hoàn tất<',
            '>Customer<' => '>Khách hàng<',
            '>Customers<' => '>Khách hàng<',
            '>Product<' => '>Sản phẩm<',
            '>Category<' => '>Danh mục<',
            '>Categories<' => '>Danh mục<',
            '>Name<' => '>Tên<',
            '>Email<' => '>Email<',
            '>Phone<' => '>Số điện thoại<',
            '>Address<' => '>Địa chỉ<',
            '>Message<' => '>Tin nhắn<',
            '>Description<' => '>Mô tả<',
            '>Content<' => '>Nội dung<',
            '>Title<' => '>Tiêu đề<',
            '>Photo<' => '>Hình ảnh<',
            '>Banner<' => '>Banner<',
            '>Logo<' => '>Logo<',
            '>Icon<' => '>Biểu tượng<',
            '>Price<' => '>Giá<',
            '>Quantity<' => '>Số lượng<',
            '>Total<' => '>Tổng<',
            '>Action<' => '>Thao tác<',
            '>Actions<' => '>Thao tác<',
            '>Serial<' => '>STT<',
            '>Date<' => '>Ngày<',
            '>Time<' => '>Thời gian<',
            '>Payment<' => '>Thanh toán<',
            '>Shipping<' => '>Vận chuyển<',
            '>Back<' => '>Quay lại<',
            '>Close<' => '>Dong<',
            '>Cancel<' => '>Huy<',
            '>Yes<' => '>Co<',
            '>No<' => '>Không<',
            '>Are you sure?<' => '>Bạn có chắc chắn không?<'
        );

        return str_replace(array_keys($map), array_values($map), $html);
    }
}
